### ISSUE TITLE
Link to Day 1 slides: the basics broken

### ISSUE THREAD

**Issue by Lextuga007** [spcanelon/xaringan-basics-and-beyond#4]
I get a 404 broken url when I click on the first day slides link. https://spcanelon.github.io/xaringan-basics-and-beyond/static/slides/day-01-basics.html

**Comment by spcanelon** [comment]
Thanks very much Zoë!
The link on the [course site](https://spcanelon.github.io/xaringan-basics-and-beyond/index.html) is fixed now and the new url it points to is: https://spcanelon.github.io/xaringan-basics-and-beyond/slides/day-01-basics.html
