### ISSUE TITLE
Default and NHSRTheme Visual Examples Tab on Slides

### ISSUE THREAD

**Issue by LaurieLBaker** [spcanelon/xaringan-basics-and-beyond#8]
Could you add a tab showing the visual output of the css files for the default and modified nhsrtheme? This would be a nice visual demonstration to complement the slides where you contrast the css code for the default and nhsrtheme themes:-).

**Comment by spcanelon** [comment]
I love this idea and I agree that the visual output would be a helpful companion to the code chunks 🙌

Do you think having a static visual of both (the before and after) would be best...OR...having a gif-thing that slowly transforms from one to the other? 🤔

**Comment by LaurieLBaker** [comment]
I think static would be good. I think it could either work with two pictures, or with the code/picture side by side. I think you could do it with tabs, or I don't know if there is like a slide reveal tab (where you pull across the tab to reveal the other tab?

**Comment by spcanelon** [comment]
I haven't seen anything like the slide reveal tabs you described but I think a feature like that would be so cool! And perfect for a situation like this.

Until that's an option (😉), I'll plan on doing static images. I think it could be a panelset with two panels, one for the default theme and one for the nhsr theme. And each panel could contain a side-by-side of the css code on one side and the output on the other 👍
